import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const monsterrat = Montserrat({ subsets: ["cyrillic-ext", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${monsterrat.className} antialiased text-black bg-[#F1F2F7] mx-auto container h-[100vh]`}
      >
        {children}
      </body>
    </html>
  );
}
